### ISSUE TITLE
pdb and psf mismatch 

### ISSUE THREAD

**Issue by llisabere** [wayuer19/HyRes_GPU#1]
Hi, following up the email question, I have some problem translating atomistic pdb into hyres. 

After using the provided scripts, number of atoms in the resulting psf file does not match the number of atoms in the pdb file. I attach example files (initfr158.pdb2gmx.pdb - original atomistic pdb generated by gromacs; initfr158.pdb2gmx.hyres.pdb, initfr158.pdb2gmx.hyres.psf - hyres pdb and psf): [pdbtest.tar.gz](https://github.com/wayuer19/HyRes_GPU/files/13889911/pdbtest.tar.gz) (sorry for archive, can't upload directly) 

The termini are normal in this case. I have followed the proposed procedure doing pdbfix -> at2hyres -> psfgen.

Could you please advice on why this could happen or what I might be doing wrong? Thank you for any information,
Cheers, 
Lisa

**Comment by lslumass** [comment]
How did you get the initial atomistic PDB file? I found several strange atom bonds. I’m not sure that’s the problem. Can you directly save a pdb file from your AA simulation trajectory, without any modification?

**Comment by llisabere** [comment]
> How did you get the initial atomistic PDB file? I found several strange atom bonds. I’m not sure that’s the problem. Can you directly save a pdb file from your AA simulation trajectory, without any modification?

The initial one is created with amber tleap from sequence, then somewhat equilibrated with mpipi cg force field and then backmapped to all atom amber. I did pdb2gmx to map it to charmm in case that was more suitable for hyres tools (the test one from before). I attach a 'clean' pdb from gmx mdrun -> gmx trjconv -dump 
[initr1.txt](https://github.com/wayuer19/HyRes_GPU/files/13901391/initr1.txt)

**Comment by lslumass** [comment]
It is the name of the Oxygen in C=O of the last residue. In our script, only the name of "O" can be recognized as the backbone Oxygen in each residue. I have modified the "pdbfix_res.py" to improve it. In HyRes, we have two kind of C-terminus. One is the CT3, which will be converted to CBX residue in HyRes force field. The orther one is the normal C-ter, which is -COO-. For this case, it was simply set as one normal residue ended with C-O. But you can set it as neutral or charged using "charged" option in "psfgen_hyres.py". Also, we recommend you to convert your pdb file into CHARMM style using CHARMM-GUI, where you can add different termius easily.

**Comment by llisabere** [comment]
What finally worked is indeed going through CHARMM-GUI and then using the new pdbfix_res.py.
Thank you a lot for help!
